# Generated by Django 4.2.4 on 2023-08-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendor', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
